version: '3'

services:
  omeka-s:
    build:  
      context: .
      dockerfile: Dockerfile
      args:
        root_path: /var/www/html/
    ports:
      - "9002:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/:/var/www/html/themes/
      - ./files/:/var/www/html/files/
      - ./config/:/var/www/html/config/
      - ./htaccess:/var/www/html/.htaccess
      - ./imagemagick-policy.xml:/var/www/html/imagemagick-policy.xml
    restart: "no"
