<?php
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
$libis = $this->plugin('Libis');
  $lang = $libis->getLanguage();
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage):?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<?php if($page->slug() == "teachers" || $page->slug() == "researchers"):?>
<div id="lang-switcher" class="ui-dropdown-list browse-switch" style="text-align:right;">
        <?php
          $languages = array('de' => 'DE','en'=> 'EN','es' => 'ES','et' => 'ET','fr' => 'FR',
          'mk' => 'MK','nl' => 'NL'
          );

          $path = $this->url('site/resource',['controller' => 'page', 'action' => $page->slug()], ['query' => ''], true);
        
        ?>
        <h2 class="visuallyhidden">Sprache wählen</h2>
        <?php foreach ($languages as $locale => $language): ?>
          <?php if ($locale == $lang): ?>
              <h4 class="ui-dropdown-list-trigger">
                <span class="visuallyhidden">Aktuelle Sprache: </span>
                  Language <strong><?php echo $language ?></strong></h4>
          <?php endif; ?>
        <?php endforeach; ?>
        <ul style="right:0;left:auto;">
        <?php foreach ($languages as $locale => $language): ?>
            <?php if ($locale != $lang): ?>
                  <li style="line-height:1.2 !important;"><a href="<?php echo str_replace("/".$lang,"/".$locale,$path);?>">
                      <?php echo $language ?>
                  </a></li>
            <?php endif;?>
        <?php endforeach; ?>
        </ul>
      </div>
<?php endif;?>
<div class="page-blocks">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
<script>
  $('#lang-switcher').find('.ui-dropdown-list-trigger').each(function() {
    $(this).click(function(){
      $(this).parent().toggleClass('active');
    });
  });

  $('.ui-dropdown-list-trigger').click(function(){
      $(this).parent().toggleClass('active');
  });
</script>