<?php
  $translate = $this->plugin('translate');
  $escape = $this->plugin('escapeHtml');
  $libis = $this->plugin('Libis');
  $lang = $libis->getLanguage();
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set resource browse'); ?>

<div class="preview-block">
<?php if ($this->heading && $this->heading != 'Narratives'  && $this->heading && $this->heading != 'Docutubes'  && $this->heading != 'Clippings database'): ?>
<h2><?php echo $this->heading; ?></h2>
<p>
  <?php echo $this->heading; ?>
</p>
<?php elseif($this->heading == 'Clippings database'):?>
  <h3><?php echo $this->heading; ?></h3>
<?php endif; ?>
<?php if($this->resourceType == 'item-set' || $this->heading == 'Docutubes' || $this->heading == 'Narratives'):?>
  <div class="top-browse">
    <div class="discover">Discover our collection</div>
    <h1>
      <?php if($this->heading != 'Docutubes' && $this->heading != 'Narratives'):?>
        <span class="active"><?php echo $this->translate('Clippings'); ?></span>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'narratives'], ['query' => ''], true);?>">Narratives</a>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'docutubes'], ['query' => ''], true);?>">Docutubes</a>
        </span>
      <?php elseif($this->heading == 'Narratives'):?>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'clippings'], ['query' => ''], true);?>"><?php echo $this->translate('Clippings'); ?></a></span>
        <span class="active">Narratives</span>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'docutubes'], ['query' => ''], true);?>">Docutubes</a>
        </span>
      <?php elseif($this->heading == 'Docutubes'): ?>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'clippings'], ['query' => ''], true);?>"><?php echo $this->translate('Clippings'); ?></a></span>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'narratives'], ['query' => ''], true);?>">Narratives</a>
        <span class="active">Docutubes</span>
      <?php endif; ?>
    </h1>
    
    <?php if($this->heading == 'Docutubes'):?>
      
        <?php if($lang == 'es'):?>
          <p>Los "docutubes" que se muestran en esta sección de la web son cortometrajes, de entre 2 y 7 minutos de duración, realizados por grupos de jóvenes en talleres celebrados en ocho lugares de Europa, uno en cada uno de los países socios de RETOPEA: Bruselas y Lovaina (Bélgica), Granada (España), Londres (Inglaterra), Maguncia (Alemania), Skopje (Macedonia del Norte), Tampere (Finlandia), Tartu (Estonia) y Varsovia (Polonia). El primer taller en Lovaina se celebró en febrero de 2020. Tras un retraso debido a la pandemia, el resto tuvo lugar en un periodo de dieciocho meses, entre diciembre de 2020 y mayo de 2022.</p>
          <p>Se pidió a los participantes, en su mayoría con edades comprendidas entre los 13 y los 18 años, que trabajaran en grupos de tres o cuatro, que realizaran cortometrajes para expresar sus propias ideas sobre la diversidad religiosa y la tolerancia, basándose en la colección de recortes de RETOPEA para obtener ideas e inspiración. Algunas de las películas se refieren directamente a los recortes de RETOPEA, mientras que otras están influenciadas por ellos de forma más implícita. Los jóvenes utilizaron una variedad de enfoques diferentes, incluyendo entrevistas con transeúntes o personas en sus lugares de trabajo, dibujos y subtítulos, la exploración de sus paisajes urbanos locales y la filmación de exposiciones en museos. Se les proporcionaron cámaras Go-Pro y utilizaron diversos programas de edición.</p>
          <p>A la hora de ver y evaluar los docutubos, es importante tener en cuenta que los talleres disponían de un tiempo limitado para filmar y editar. Se animó a los participantes a ver el objetivo del ejercicio de filmación no como una perfección técnica, sino como un medio para desarrollar y articular sus propias ideas sobre la tolerancia religiosa y la paz. Al verlos por ti mismo, deberías abordarlos con el mismo espíritu, como si ofrecieran una visión de las ideas y la experiencia de una muestra de los jóvenes europeos de hoy, e inspiraran a otros a aceptar el reto de hacer también docutubos. (Para más información y orientación sobre este proceso, consulte el curso gratuito en línea producido por The Open University: <a target="_blank" href="https://www.open.edu/openlearn/mod/oucontent/view.php?id=126746">Young People and Religion: Creative Learning with History</a>)</p>
        <?php elseif($lang == 'nl'):?>    
          <p>De "docutubes" in dit deel van de website zijn korte films van 2 tot 7 minuten, gemaakt door groepen jongeren tijdens workshops op acht locaties in Europa, één in elk van de RETOPEA-partnerlanden: Brussel en Leuven (België), Granada (Spanje), Londen (Engeland), Mainz (Duitsland), Skopje (Noord-Macedonië), Tampere (Finland), Tartu (Estland) en Warschau (Polen). De eerste workshop in Leuven vond plaats in februari 2020. Na een vertraging als gevolg van de Covid-pandemie vonden de overige workshops plaats over een periode van achttien maanden tussen december 2020 en mei 2022.</p>
          <p>De deelnemers, overwegend tussen 13 en 18 jaar oud en werkend in groepjes van drie of vier, maakten korte films waarin ze hun eigen ideeën over religieuze diversiteit en tolerantie tot uitdrukking brachten. Daarbij vonden ze inspiratie en maakten ze gebruik van de RETOPEA-clippings. Sommige films verwijzen rechtstreeks naar die clippings, andere zijn er op meer impliciete wijze door beïnvloed. De jongeren benaderden het onderwerp op verschillende manieren: interviews met voorbijgangers of mensen op hun werkplek, een verkenning van het stadslandschap, toelichting bij museumdisplays,… Ze gebruikten Go-Pro camera's en verschillende montagesoftwarepakketten.</p>
          <p>Bij het bekijken en evalueren van de docutubes moet men beseffen dat de workshops slechts weinig tijd lieten voor het filmen en monteren. Bij het filmen, zo werd de deelnemers ingeprent, moest er niet worden gestreefd naar technische perfectie. Het was eerder als een middel om hun eigen ideeën over religieuze tolerantie en vrede te ontwikkelen en te verwoorden. Bij het bekijken van de films dient u dat in het achterhoofd te houden. Deze 'docutubes' belichten de ideeën en ervaringen van een aantal jonge Europeanen van vandaag, en dienen als inspiratie voor anderen die de uitdaging aangaan om ook zulke films te maken. 
Zie voor meer informatie en begeleiding bij dit proces de gratis online cursus van The Open University: <a target="_blank" href="https://www.open.edu/openlearn/mod/oucontent/view.php?id=126746">Young People and Religion: Creative Learning with History</a>)</p>
        <?php elseif($lang == 'mk'):?>    
          <p>„Docutubes“ или документарци прикажани во овој дел од веб-страницата се кратки филмови, во должина од 2 до 7 минути, направени од групи млади луѓе на работилници на осум локации низ Европа, по една во секоја од земјите партнери на RETOPEA: Брисел и Лувен. (Белгија), Гранада (Шпанија), Лондон (Англија), Мајнц (Германија), Скопје (Северна Македонија), Тампере (Финска), Тарту (Естонија) и Варшава (Полска). Првата работилница во Лувен се одржа во февруари 2020 година. Со доцнење поради пандемијата, остатокот се одржа во период од осумнаесет месеци помеѓу декември 2020 година и мај 2022 година.</p>
          <p>Учесниците, претежно на возраст меѓу 13 и 18 години и работејќи во групи од тројца или четворица, беа замолени да направат кратки филмови за да ги изразат своите идеи за религиозната разноликост  и толеранција, потпирајќи се на колекцијата исечоци на RETOPEA за идеи и инспирација. Некои од филмовите се однесуваат директно на исечоците од RETOPEA; други се под нивно влијание на поимплицитен начин. Младите користеа различни пристапи, вклучувајќи интервјуа со случајни минувачи или луѓе на нивните работни места, цртежи и натписи, истражување на нивните локални градски пејзажи и снимање музејски поставки. Им беа обезбедени Go-Pro камери и користеа различни софтверски пакети за уредување.</p>
          <p>При гледањето и оценувањето на документарците, важно е да се знае дека работилниците овозможија ограничено време за снимање и монтажа. Учесниците беа охрабрени да  гледаат  на вежбата за правење филм не како на техничко совршенство, туку како на средство за развивање и артикулирање на сопствените идеи за религиозната толеранција и мир. И вие гледајки ги документарците, треба да им пристапите во истиот дух, односно да понудите поглед во идеите и искуството на примери од денешните млади Европејци и да ги инспирирате другите да го прифатат овој предизвик   и да направат  документарци. (За дополнителни информации и насоки за овој процес ве молиме погледнете го бесплатниот онлајн курс подготвен од
The Open University: <a target="_blank" href="https://www.open.edu/openlearn/mod/oucontent/view.php?id=126746">Young People and Religion: Creative Learning with History</a>)</p>
        <?php elseif($lang == 'et'):?>      
          <p>Veebisaidi selles osas kuvatavad "veebidokid" on lühifilmid pikkusega 2-7 minutit, mille on teinud noorte rühmad kaheksas kohas üle Euroopa (üks igas RETOPEA partnerriigis) toimunud töötubades: Brüssel ja Leuven (Belgia), Granada (Hispaania), London (Inglismaa), Mainz (Saksamaa), Skopje (Põhja-Makedoonia), Tampere (Soome), Tartu (Eesti) ja Varssavi (Poola). Esimene seminar Leuvenis toimus 2020. aasta veebruaris. Pärast pandeemiast tingitud viivitust toimusid ülejäänud seminarid kaheksateistkümne kuu jooksul ajavahemikus 2020. aasta detsembrist kuni 2022. aasta maini.</p>
          <p>Osalejatel, kes olid valdavalt 13-18-aastased ja töötasid kolme- või neljaliikmelistes rühmades, paluti teha lühifilme, et väljendada oma ideid usulisest mitmekesisusest ja sallivusest, kasutades ideede ja inspiratsiooni saamiseks RETOPEA väljalõigete kollektsiooni. Mõned filmid viitavad otseselt RETOPEA väljalõigetele; teised on neist mõjutatud kaudselt. Noored kasutasid erinevaid lähenemisviise, sealhulgas intervjuusid möödakäijate või oma töökohal töötavate inimestega, joonistusi ja filmiklippe, oma kohaliku linnapildi uurimist ja muuseumide väljapanekute filmimist. Neile anti Go-Pro kaamerad ja nad kasutasid mitmesuguseid montaažiprogramme.</p>
          <p>Veebidokkide vaatamisel ja hindamisel on oluline arvestada, et töötubades oli filmimiseks ja montaažiks piiratud aeg. Osalejaid julgustati nägema filmitegemise eesmärgina mitte tehnilist täiuslikkust, vaid pigem vahendit, mille abil arendada ja sõnastada oma ideid usulise sallivuse ja rahu kohta. Kui te vaatate neid, siis peaksite lähenema neile samas vaimus: nad annavad ülevaate tänapäeva noorte eurooplaste ideedest ja kogemustest ning inspireerivad teisi, et nemadki võtaksid ette teha veebidokki. (Täiendavat teavet ja juhiseid selle protsessi kohta leiate tasuta veebikursusest, mille on koostanud The Open University: <a target="_blank" href="https://www.open.edu/openlearn/mod/oucontent/view.php?id=126746">Young People and Religion: Creative Learning with History</a>)</p>
        <?php elseif($lang == 'de'):?>
          <p>Bei den in diesem Bereich der Website gezeigten " Docutubes " handelt es sich um Kurzfilme von zwei bis sieben Minuten Länge, die von Gruppen junger Menschen in Workshops an acht Orten in ganz Europa gedreht wurden, in jedem der RETOPEA-Partnerländer: Brüssel und Leuven (Belgien), Granada (Spanien), London (England), Mainz (Deutschland), Skopje (Nordmazedonien), Tampere (Finnland), Tartu (Estland) und Warschau (Polen). Der erste Workshop in Leuven fand im Februar 2020 statt. Nach einer pandemiebedingten Verzögerung fand der Rest über einen Zeitraum von achtzehn Monaten zwischen Dezember 2020 und Mai 2022 statt.</p>
          <p>Die Teilnehmer, die überwiegend zwischen 13 und 18 Jahren alt waren und in Dreier- oder Vierergruppen arbeiteten, wurden gebeten, kurze Filme zu drehen, um ihre eigenen Ideen über religiöse Vielfalt und Toleranz auszudrücken. Dabei stützten sie sich auf die Clipping-Sammlung von RETOPEA, um Ideen und Anregungen zu erhalten. Einige der Filme beziehen sich direkt auf die RETOPEA Clippings, andere sind eher implizit von ihnen beeinflusst. Die jungen Leute nutzten eine Vielzahl unterschiedlicher Ansätze, darunter Interviews mit Passanten oder mit Menschen an ihren Arbeitsplätzen, Zeichnungen und untertitelte Bilder, die Erkundung ihres örtlichen Stadtbildes und das Filmen von Museumsausstellungen. Sie bekamen Go-Pro-Kameras zur Verfügung gestellt und benutzten verschiedene Bearbeitungsprogramme.</p>
          <p>Bei der Betrachtung und Bewertung der Docutubes ist es wichtig, sich bewusst zu machen, dass in den Workshops nur begrenzte Zeit für das Filmen und Bearbeiten zur Verfügung stand. Die Teilnehmer wurden ermutigt, das Ziel des Filmemachens nicht in der technischen Perfektion zu sehen, sondern den Film als ein Mittel zu verstehen, um ihre eigenen Ideen zu religiöser Toleranz und Frieden zu entwickeln und zu artikulieren. Wenn Sie die Filme ansehen, sollten Sie sie in demselben Sinne betrachten: dass sie Einblicke in die Ideen und Erfahrungen junger Europäer von heute bieten und andere dazu anregen, sich der Herausforderung zu stellen, ebenfalls Dokumentarfilme zu drehen. (Weitere Informationen und Anleitungen zu diesem Prozess finden Sie in einem kostenlosen Online-Kurs, bereitgestellt von The Open University: : <a target="_blank" href="https://www.open.edu/openlearncreate/course/view.php?id=8726">Junge Menschen und Religion: Kreatives Lernen mit Geschichte</a>)</p>
        <?php elseif($lang == 'fr'):?>  
          <p>Les "docutubes" présentés dans cette section du site web sont des courts métrages, d'une durée de 2 à 7 minutes, réalisés par des groupes de jeunes dans le cadre d'ateliers organisés dans huit endroits en Europe, un dans chacun des pays partenaires de RETOPEA : Bruxelles et Louvain (Belgique), Grenade (Espagne), Londres (Angleterre), Mayence (Allemagne), Skopje (Macédoine du Nord), Tampere (Finlande), Tartu (Estonie) et Varsovie (Pologne). Le premier atelier à Louvain a eu lieu en février 2020. Après un retard dû à la pandémie, les autres se sont déroulés sur une période de dix-huit mois entre décembre 2020 et mai 2022.</p>
          <p>Les participants, âgés pour la plupart de 13 à 18 ans et travaillant par groupes de trois ou quatre, ont été invités à réaliser des courts métrages pour exprimer leurs propres idées sur la diversité religieuse et la tolérance, en s'inspirant de la collection d'extraits de source RETOPEA. Certains films font directement référence aux extraits, d'autres sont influencés par elles de manière plus implicite. Les jeunes ont utilisé une variété d'approches différentes, y compris des entretiens avec des passants ou des personnes sur leur lieu de travail, des dessins et des légendes, l'exploration de leurs paysages urbains locaux et le tournage d'expositions dans des musées. Ils ont été équipés de caméras Go-Pro et ont utilisé divers logiciels de montage.</p>
          <p>Lors du visionnage et de l'évaluation des docutubes, il est important d'être conscient que les ateliers n'ont laissé que peu de temps pour le tournage et le montage. Les participants ont été encouragés à considérer l'objet de l'exercice de réalisation du film non pas comme une perfection technique, mais plutôt comme un moyen de développer et d'articuler leurs propres idées sur la tolérance religieuse et la paix. En les visionnant vous-même, vous devriez les aborder dans le même esprit, comme offrant un aperçu des idées et de l'expérience d'un échantillon de jeunes Européens d'aujourd'hui, et inspirant d'autres personnes à relever le défi de réaliser également des docutubes. (Pour de plus amples informations et des conseils sur ce processus, veuillez consulter le cours en ligne gratuit produit par The Open University: <a target="_blank" href="https://www.open.edu/openlearn/mod/oucontent/view.php?id=126746">Young People and Religion: Creative Learning with History</a>)</p>
        <?php else:?>
          <p>The ‘docutubes’ displayed in this section of the website are short films, ranging from 2 to 7 minutes in length, made by groups of young people in workshops in eight locations across Europe, one in each of the RETOPEA partner countries: Brussels and Leuven (Belgium), Granada (Spain), London (England), Mainz (Germany), Skopje (North Macedonia), Tampere (Finland), Tartu (Estonia) and Warsaw (Poland). The first workshop in Leuven was held in February 2020. After a delay due to the pandemic, the remainder took place over a period of eighteen months between December 2020 and May 2022.</p> 
          <p>The participants, predominantly aged between 13 and 18 and working in groups of three or four, were asked to make short films to express their own ideas about religious diversity and tolerance, drawing on the RETOPEA clippings collection for ideas and inspiration. Some of the films refer directly to RETOPEA clippings; others are influenced by them in more implicit ways. The young people used a variety of different approaches, including interviews with passers-by or people in their workplaces, drawings and captions, exploration of their local cityscapes and filming of museum displays. They were provided with Go-Pro cameras and used a variety of editing software packages.</p>
          <p>In viewing and evaluating the docutubes, it is important to be aware that the workshops allowed limited time for filming and editing. Participants were encouraged to see the object of the film-making exercise not as technical perfection, but rather as a means to develop and articulate their own ideas on religious toleration and peace. In viewing them for yourself you should approach them in the same spirit, as offering insights into the ideas and experience of a sample of today’s young Europeans, and inspiring others to rise to the challenge of also making docutubes. (For further information and guidance on this process please see the free online course produced by 
The Open University: <a target="_blank" href="https://www.open.edu/openlearn/mod/oucontent/view.php?id=126746">Young People and Religion: Creative Learning with History</a>)</p>
        <?php endif;?>  
    
    <?php endif;?>     

    <?php if($this->heading != 'Docutubes' && $this->heading != 'Narratives'):?>
      <div id="lang-switcher" class="ui-dropdown-list browse-switch">
        <?php
          $languages = array('de' => 'DE','en'=> 'EN','es' => 'ES','et' => 'ET','fr' => 'FR',
          'mk' => 'MK','nl' => 'NL'
          );
        
          if($this->heading == 'Narratives'):
            $path = $this->url('site/resource',['controller' => 'page', 'action' => 'narratives'], ['query' => ''], true);
          else:
            $path = $this->url('site/resource',['controller' => 'page', 'action' => 'clippings'], ['query' => ''], true);
          endif;
        ?>
        <h2 class="visuallyhidden">Sprache wählen</h2>
        <?php foreach ($languages as $locale => $language): ?>
          <?php if ($locale == $lang): ?>
              <h4 class="ui-dropdown-list-trigger">
                <span class="visuallyhidden">Aktuelle Sprache: </span>
                  Language <strong><?php echo $language ?></strong></h4>
          <?php endif; ?>
        <?php endforeach; ?>
        <ul>
        <?php foreach ($languages as $locale => $language): ?>
            <?php if ($locale != $lang): ?>
                  <li><a href="<?php echo str_replace($lang,$locale,$path);?>">
                      <?php echo $language ?>
                  </a></li>
            <?php endif;?>
        <?php endforeach; ?>
        </ul>
      </div>
      <?php 
        $placeholder_array = array(
          "en" => "search the clippings",
          "nl" => "zoek de knipsels",
          "mk" => "пребарајте ги исечоците",
          "fr" => "rechercher les coupures",
          "de" => "durchsuchen sie die ausschnitte",
          "es" => "buscar los recortes",
          "et" => "otsi väljalõikeid",
        );
        if(isset($placeholder_array[$lang])):
          $placeholder = $placeholder_array[$lang];
        else:
          $placeholder = "search the clippings";
        endif;    
      ?>   
      <div id="search">
          <?php
          $searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
          ?>

          <form action="<?php echo $this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
      );?>" id="search-form">
              <input type="text" name="fulltext_search" value="<?php echo $searchValue; ?>"
                  placeholder="<?php echo $placeholder; ?>"
                  aria-label="<?php echo $placeholder; ?>">
              <button type="submit"><?php echo $translate('Search'); ?></button>
          </form>
      </div>
      <?php if($this->heading != 'Narratives' && $this->heading != 'Docutubes'):?>
        <br> 
        <?php if($lang == 'es'):?>
          <p>¿Te has preguntado alguna vez cómo se enfrentaban las personas del pasado a las diferencias y conflictos entre las distintas religiones? Te damos la bienvenida a la colección RETOPEA. Aquí podrás descubrir ejemplos de cómo la gente en Europa y más allá, en muchos períodos históricos diferentes, ha pensado y experimentado diferentes creencias y prácticas religiosas y ha encontrado maneras de vivir juntos. Nuestra colección incluye más de 400 "fragmentos". Se trata de textos breves, imágenes o vídeos que exploran diferentes aspectos de la diversidad religiosa, la tolerancia y la paz en muchos países diferentes, en el pasado y en el presente. Algunos de los ejemplos tratados pueden resultarte muy familiares, mientras que otros pueden revelar nuevas ideas y sorprenderte.</p>
          <p>Los fragmentos abarcan 12 temas; puedes hacer clic en cada uno de ellos para encontrar el que más le interese. También puedes buscar en la colección RETOPEA utilizando tus propios términos de búsqueda. Cuando encuentres un recorte que le llame especialmente la atención, consulta el apartado "Está referenciado por", ya que te llevará a otros fragmentos relacionados que pueden resultarte interesantes.</p>
          <p>Puedes explorar la colección RETOPEA por tu cuenta, pero los fragmentoss también pueden utilizarse como material educativo en escuelas, museos o grupos de jóvenes. </p>
          <p>Cada fragmento viene acompañado de una serie de preguntas para fomentar el pensamiento crítico sobre los temas que plantea.  </p>
          <p>El equipo de RETOPEA ha desarrollado un modelo de talleres en los que los y las adolescentes realizan cortometrajes inspirados en los fragmentos de RETOPEA. Llamamos a estas películas "docutubes", ya que su estilo es similar al de los vídeos de Vlogging en YouTube. Si eres profesor o educador y quieres saber cómo organizar un taller de docutubes o cómo utilizar los recursos de RETOPEA con tus alumnos, <a href="https://retopea.eu/s/start/page/contact">haz clic aquí</a>.</p>
        <?php elseif($lang == 'nl'):?>    
          <p>Heb je je ooit afgevraagd hoe mensen in het verleden omgingen met de verschillen en conflicten tussen religies? Welkom bij de RETOPEA-collectie! Hier vind je tal van voorbeelden van hoe mensen doorheen verschillende tijdvakken, en dit zowel in Europa als daarbuiten, hebben nagedacht over de verschillen tussen religieuze overtuigingen, en over hoe ze vanuit hun ervaringen manieren vonden om samen te leven. </p>
          <p>Onze collectie omvat meer dan 400 'knipsels'. Dat zijn korte teksten, beelden of video's die aspecten van religieuze diversiteit, tolerantie en vrede belichten, dit in tal van landen en historische periodes. Sommige voorbeelden zijn je misschien al bekend, andere zullen je beslist verrassen en nieuwe inzichten bijbrengen.</p>
          <p>De knipsels bestrijken 12 thema’s waar je op kan doorklikken. Je kan de RETOPEA-collectie ook doorzoeken met uw eigen zoektermen. Wanneer je op een interessant knipsel stoot, kijk dan zeker ook eens naar de rubriek 'Is referenced by'. Die leidt je naar verwante en misschien ook interessante bronnen.</p>
          <p>Je kan de RETOPEA-collectie vrij verkennen. Maar de knipsels kunnen ook worden gebruikt als educatief materiaal in scholen, musea of jeugdgroepen. </p>
          <p>Bij elk knipsel hoort een reeks vragen die aanzetten tot kritisch denken over de behandelde onderwerpen.</p>
          <p>Het RETOPEA-team heeft een model ontwikkeld voor workshops waar tieners zelf korte films maken, geïnspireerd op de RETOPEA-knipsels. We noemen deze films 'docutubes' omdat ze qua stijl lijken op vlogvideo's op YouTube. Ben je leraar of opvoeder bent en wil je meer info over hoe zelf met je leerlingen een docutube-workshop te organiseren en daarvoor de RETOPEA-bronnen te gebruiken, <a href="https://retopea.eu/s/start/page/contact">klik dan hier</a>.</p>
        <?php elseif($lang == 'mk'):?>    
          <p>Дали некогаш сте се запрашале како луѓето во минатото се справувале со разликите и конфликтите меѓу различните религии? Добредојдовте во збирката на RETOPEA! Овде можете да откриете примери за тоа како луѓето во Европа и пошироко, во многу различни историски периоди, размислувале и доживеале различни религиозни верувања и практики и нашле начини за заеднички живот. Нашата збирка вклучува повеќе од 400 “исечоци“. Тоа се кратки текстови, слики или видеа кои истражуваат различни аспекти на верската различност, толеранција и мир од многу различни земји во минатото и сегашноста. Некои од опфатените примери можеби ви се многу познати - други може да откријат нови сознанија и да ве изненадат.</p>
          <p>Исечоците опфаќаат 12 теми - можете да кликнете на секоја од овие теми за да ви помогне да го пронајдете она што најмногу ве интересира. Можете исто така да ја пребарувате збирката на RETOPEA користејќи ги вашите сопствени термини за пребарување. Кога ќе најдете исечок што особено ви го привлекува вниманието, проверете го насловот “Се референцира со“  бидејќи тоа ве води до други поврзани исечоци што можеби ќе ви бидат интересни.</p>
          <p>Можете сами да ја истражите збирката RETOPEA - но исечоците може да се користат и како едукативни материјали во училишта, музеите или страна на групи од млади луѓе.</p>
          <p>Секој исечок доаѓа со збир на прашања за поттикнување на критичко размислување за прашањата што ги отвара.</p>
          <p>Тимот на RETOPEA разви модел за работилници каде што тинејџерите снимаат кратки филмови инспирирани од исечоците од RETOPEA. Овие филмови ги нарекуваме “докутуби“ бидејќи по стил се слични на видеата за блогирање на You Tube. Ако сте наставник или едукатор и сакате да дознаете како сами може да водите работилница за doкутуби или за други начини на кои можете да ги користите ресурсите на RETOPEA со вашите ученици - <a href="https://retopea.eu/s/start/page/contact">ве молиме кликнете овде</a>.</p>
        <?php elseif($lang == 'et'):?>      
          <p>Kas olete kunagi mõelnud, kuidas inimesed minevikus tegelesid erinevate religioonide vahel tekkinud lahkhelide ja konfliktidega? Tere tulemast tutvuma RETOPEA koguga! Siin leiate näiteid sellest, kuidas inimesed erinevatel ajalooperioodidel Euroopas ja mujal kogesid erinevaid usundeid ja tavasid, nende üle mõtisklesid ning leidsid kooselamise viise. Meie kogus on üle 400 "väljalõike". Need on lühikesed tekstid, pildid või videod, mis uurivad usulise mitmekesisuse, sallivuse ja rahu erinevaid aspekte paljudest erinevatest riikidest minevikus ja tänapäeval. Mõned näited võivad olla teile väga tuttavad - teised võivad teile uusi teadmisi anda ja teid üllatada. </p>
          <p>Väljalõiked hõlmavad 12 teemat - võite klõpsata igale teemale, et leida teie jaoks kõige huvitavam. Samuti saate RETOPEA kogust otsingusõnu kasutades teemasid otsida. Kui leiate väljalõike, mis äratab teie tähelepanu, vaadake pealkirja "on viidatud", sest see viib teid teiste seotud väljavõtete juurde, mis võivad teid huvitada.</p>
          <p>RETOPEA kogu saate uurida ise, kuid väljalõikeid saab kasutada ka õppematerjalina koolides, muuseumides või noortegruppides. </p>
          <p>Iga väljalõige on varustatud küsimuste kogumiga, et julgustada kriitilist mõtlemist selles tõstatatud teemade üle.  </p>
          <p>RETOPEA meeskond on välja töötanud mudeli töötubade jaoks, kus teismelised teevad RETOPEA väljalõigetest inspireeritud lühifilme. Me nimetame neid filme "veebidokkideks", kuna need on oma stiililt sarnased YouTube'i videoblogide klippidega. Kui oled õpetaja või koolitaja ja soovid teada saada, kuidas ise veebidoki töötuba korraldada või milliseid muid võimalusi leidub RETOPEA ressursside kasutamiseks koos oma õpilastega,<a href="https://retopea.eu/s/start/page/contact"> siis kliki siia</a>.</p>
        <?php elseif($lang == 'de'):?>
          <p>Hast du dich jemals gefragt, wie Menschen in der Vergangenheit mit Unterschieden und Konflikten zwischen verschiedenen Religionen umgegangen sind? Willkommen in der RETOPEA-Sammlung! Hier kannst du Beispiele dafür entdecken, wie Menschen in Europa und darüber hinaus in verschiedenen historischen Epochen über unterschiedliche religiöse Überzeugungen und Gebräuche gedacht haben und wie sie Wege des Zusammenlebens gefunden haben. Unsere Sammlung umfasst mehr als 400 "Clippings". Dabei handelt es sich um kurze Texte, Bilder oder Videos, die verschiedene Aspekte von religiöser Vielfalt, Toleranz und Frieden aus vielen verschiedenen Ländern in Vergangenheit und Gegenwart beleuchten. Einige der behandelten Beispiele werden dir vielleicht sehr vertraut sein – andere können dir neue Einsichten vermitteln und dich überraschen.</p>
          <p>Die Clippings decken 12 Themen ab – du kannst jedes dieser Themen anklicken, um das zu finden, was für dich am interessantesten ist. Du kannst die RETOPEA-Sammlung auch mit deinen eigenen Suchbegriffen durchsuchen. Wenn du ein Clipping findest, das deine Aufmerksamkeit erregt, solltest du auf den Hinweis "Wird referenziert von" achten, da dieser dich zu anderen verwandten Clippings führt, die für dich auch interessant sein könnten.</p>
          <p>Du kannst die RETOPEA-Sammlung auf eigene Faust erkunden – die Clippings können aber auch als Unterrichtsmaterial in Schulen, Museen oder Jugendgruppen verwendet werden. </p>
          <p>Zu jedem Clipping gibt es eine Reihe von Fragen, die zum kritischen Nachdenken über die darin angesprochenen Themen anregen sollen.  </p>
          <p>Das RETOPEA-Team hat ein Modell für Workshops entwickelt, in denen Jugendliche Kurzfilme drehen, die von den RETOPEA-Clippings inspiriert sind. Wir nennen diese Filme 'Docutubes', da sie dem Stil von Vlogging-Videos auf YouTube ähneln. Wenn Sie Lehrer oder Erzieher sind und wissen möchten, wie Sie selbst einen Docutube-Workshop durchführen oder wie Sie die RETOPEA-Ressourcen mit Ihren Schülern nutzen können, <a href="https://retopea.eu/s/start/page/contact">klicken Sie bitte hier</a>.</p>
        <?php elseif($lang == 'fr'):?>  
          <p>Vous êtes-vous déjà demandé comment les différences et les conflits entre les différentes religions étaient traités dans le passé ? Bienvenue dans la collection RETOPEA ! Vous y découvrirez des exemples de la façon dont les gens en Europe et au-delà, à différentes périodes historiques, ont pensé et vécu les différentes croyances et pratiques religieuses et ont trouvé des moyens de vivre ensemble. Notre collection comprend plus de 400 "coupures". Il s'agit de courts textes, d'images ou de vidéos qui explorent différents aspects de la diversité religieuse, de la tolérance et de la paix dans de nombreux pays du passé et du présent. Certains des exemples couverts peuvent vous être très familiers - d'autres peuvent vous révéler de nouvelles perspectives et vous surprendre.  </p>
          <p>Les coupures couvrent 12 thèmes - vous pouvez cliquer sur chacun de ces thèmes pour vous aider à trouver ce qui vous intéresse le plus. Vous pouvez également effectuer une recherche dans la collection RETOPEA en utilisant vos propres termes de recherche. Lorsque vous trouvez une coupure qui retient particulièrement votre attention, vérifiez la rubrique "Est référencée par" car elle vous conduit à d'autres coupures connexes qui pourraient vous intéresser. </p>
          <p>Vous pouvez explorer la collection RETOPEA par intérêt personnel, mais les coupures peuvent également être utilisées comme matériel pédagogique dans les écoles, les musées ou avec les groupes de jeunes.  </p>
          <p>Chaque coupure est accompagnée d'une série de questions visant à encourager la réflexion critique sur les problèmes qu'elle soulève.   </p>
          <p>L'équipe RETOPEA a mis au point un modèle d'atelier dans lequel les adolescents réalisent des courts métrages inspirés des coupures RETOPEA. Nous appelons ces films "docutubes" car leur style est similaire à celui des vidéos des vlogueurs sur YouTube. Si vous êtes un enseignant ou un éducateur et que vous souhaitez savoir comment organiser vous-même un atelier docutube ou découvrir d'autres façons d'utiliser les ressources RETOPEA avec votre public cible, <a href="https://retopea.eu/s/start/page/contact">veuillez cliquer ici.</a> </p>
        <?php else:?>
          <p>Ever wondered about how people in the past dealt with differences and conflicts between different religions? Welcome to the RETOPEA collection! Here you can discover examples of how people in Europe and beyond, in many different historical periods, have thought about and experienced different religious beliefs and practices and found ways of living together. Our collection includes more than 400 &lsquo;clippings&rsquo;. These are short texts, images or videos that explore different aspects of religious diversity, tolerance and peace from many different countries in the past and present. Some of the examples covered may be very familiar to you - others may reveal new insights and surprise you.&nbsp;</p>
          <p>The clippings cover 12 themes - you can click on each of these themes to help you find what is of most interest to you. You can also search the RETOPEA collection using your own search terms. When you find a clipping that particularly catches your attention, check out the heading &lsquo;Is referenced by&rsquo; as this leads you to other related clippings you might find interesting.</p>
          <p>You can explore the RETOPEA collection by yourself - but the clippings can also be used as educational materials in schools, museums or youth groups.&nbsp;</p>
          <p>Each clipping comes with a set of questions to encourage critical thinking about the issues it raises. &nbsp;</p>
          <p>The RETOPEA team have developed a model for workshops where teenagers make short films inspired by the RETOPEA clippings. We call these films &lsquo;docutubes&rsquo; as they are similar in style to Vlogging videos on YouTube. If you are a teacher or educator and would like to find out how to run a docutube workshop yourself or about other ways you can use the RETOPEA resources with your students - <a href="https://retopea.eu/s/start/page/contact">please click here</a>.</p>
          
        <?php endif;?>
      
          
      <?php endif;?>  

    <?php endif;?>
    
    <?php echo $this->searchFilters(); ?>
  </div>
<?php endif;?>
<?php if($this->resourceType == 'item-set'):?>
  <div class="item-showcase item-set-showcase">
      <?php foreach ($this->resources as $itemSet): ?>
      <div class="item resource">
        <?php if($media = $itemSet->thumbnail()):?>
          <a href="<?php echo $itemSet->url();?>">
          <div class="media" style="background:url(<?php echo $media->assetUrl('square')?>)"></div>
          </a>
        <?php else:?>
          <div class="media" style="background:#ccc;"></div>
        <?php endif;?>
        <div class="text">
          <?php if($itemSet->value('dcterms:title',array('lang' => $lang))):?>
            <h4><?php echo $itemSet->link($itemSet->value('dcterms:title',array('lang' => $lang))); ?></h4>
          <?php else:?>
            <h4><?php echo $itemSet->link($itemSet->value('dcterms:title')); ?></h4>  
          <?php endif;?> 
        </div>
      </div>
      <?php endforeach; ?>
  </div>

<?php elseif ($this->linkText == 'Browse all news'):?>
  <div class="resource-list preview">
  <?php
  $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
  $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
  foreach ($this->resources as $resource):
      $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
      $body = $resource->value($bodyTerm);
  ?>
      <div class="news-item">
        <div class="thumbnail">
          <?php echo $resource->linkRaw($this->thumbnail($resource, 'square')); ?>
        </div>
        <div class="body">
          <h4><?php echo $resource->link($heading); ?></h4>
          <div class="date">
            <?php if($resource->value('dcterms:date')):?>
              <?php echo date('d-m-Y',strtotime($resource->value('dcterms:date')));?>
            <?php endif;?>
          </div>
          <div class="description">
            <?php if($resource->value('dcterms:alternative')):?>
              <?php echo $resource->value('dcterms:alternative');?>
            <?php endif;?>
          </div>
          <div class="subject">
            <?php if($resource->value('dcterms:subject')):?>
              <?php echo $resource->value('dcterms:subject');?>
            <?php endif;?>
          </div>
        </div>
      </div>
  <?php endforeach; ?>
  <?php
  if ($this->linkText):
      echo $this->hyperlink($this->linkText, $this->url(
          'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
      ));
  endif;
  ?>
  </div>

<?php elseif($this->heading == "Docutubes"):?>
  <div class="resource-list masonry">
    <?php
    $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
    $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
    foreach ($this->resources as $resource):
        $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
        $body = $resource->value($bodyTerm);
        $type = $resource->resourceTemplate();
        if($type){
          $type = $resource->resourceTemplate()->label();
        }else{
          $type = false;
        }
    ?>
        <div class="<?php echo $this->resourceType; ?> resource">
          <a href="https://retopea.eu/s/en/item/<?php echo $resource->id();?>"><?php echo $this->thumbnail($resource, 'square'); ?></a>
          <div class="body">
            <h4 style="height: 5rem;"><a href="https://retopea.eu/s/en/item/<?php echo $resource->id();?>"><?php echo $heading; ?></a></h4>
            <?php if ($body): ?>
              <!--<div class="description"><?php echo $body; ?></div>-->
            <?php endif; ?>
            <?php if ($type == 'Docutube'): ?>
              <div class="language"><?php echo $resource->value('dcterms:language');?></div>
            <?php endif;?>
          </div>
        </div>
    <?php endforeach; ?>
    </div>

<?php elseif($this->heading == "Narratives"):?>
    <div class="resource-list">
    <?php foreach ($this->resources as $resource):?>
      <?php $heading = $resource->value('dcterms:title',array("lang" => $lang))->asHtml();?>
      <div>
        <h3><a href="<?php echo $resource->url();?>"><?php echo $heading;?></a></h3>      
      </div>
    <?php endforeach; ?>
    </div>
<?php else:?>
    <div class="resource-list masonry preview homepage">
    <?php
    $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
    $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
    foreach ($this->resources as $resource):
        $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
        $body = $resource->value($bodyTerm);
        $type = $resource->resourceTemplate();
        if($type){
          $type = $resource->resourceTemplate()->label();
        }else{
          $type = false;
        }
    ?>
        <div class="<?php echo $this->resourceType; ?> resource">
          <a href="https://retopea.eu/s/en/item/<?php echo $resource->id();?>"><?php echo $this->thumbnail($resource, 'square'); ?></a>
          <div class="body">
            <h4><a href="https://retopea.eu/s/en/item/<?php echo $resource->id();?>"><?php echo $heading; ?></a></h4>
            <?php if ($body): ?>
              <!--<div class="description"><?php echo $body; ?></div>-->
            <?php endif; ?>
            <?php if ($type == 'Docutube'): ?>
              <div class="language"><?php echo $resource->value('dcterms:language');?></div>
            <?php endif;?>
          </div>
        </div>
    <?php endforeach; ?>
    </div>
   
      <div class="more-news-showcase">
        <a class="btn" href="https://retopea.eu/s/en/page/clippings"><?php echo $this->linkText;?></a>
      </div>
   
<?php endif;?>


</div>
<script>
  $('#lang-switcher').find('.ui-dropdown-list-trigger').each(function() {
    $(this).click(function(){
      $(this).parent().toggleClass('active');
    });
  });

  $('.ui-dropdown-list-trigger').click(function(){
      $(this).parent().toggleClass('active');
  });
</script>
