<?php
  $translate = $this->plugin('translate');
  $escape = $this->plugin('escapeHtml');
  $libis = $this->plugin('Libis');
  $lang = $libis->getLanguage();
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set resource browse'); ?>

<div class="preview-block">
<?php if ($this->heading && $this->heading != 'Narratives'  && $this->heading && $this->heading != 'Docutubes'  && $this->heading != 'Clippings database'): ?>
<h2><?php echo $this->heading; ?></h2>
<p>
  <?php echo $this->heading; ?>
</p>
<?php elseif($this->heading == 'Clippings database'):?>
  <h3><?php echo $this->heading; ?></h3>
<?php endif; ?>
<?php if($this->resourceType == 'item-set' || $this->heading == 'Docutubes'):?>
  <div class="top-browse">
    <div class="discover">Discover our collection</div>
    <h1>
      <?php if($this->heading != 'Docutubes' && $this->heading != 'Narratives'):?>
        <span class="active"><?php echo $this->translate('Clippings'); ?></span>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'narratives'], ['query' => ''], true);?>">Narratives</a>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'docutubes'], ['query' => ''], true);?>">Docutubes</a>
        </span>
      <?php elseif($this->heading == 'Narratives'):?>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'clippings'], ['query' => ''], true);?>"><?php echo $this->translate('Clippings'); ?></a></span>
        <span class="active">Narratives</span>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'docutubes'], ['query' => ''], true);?>">Docutubes</a>
        </span>
      <?php elseif($this->heading == 'Docutubes'): ?>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'clippings'], ['query' => ''], true);?>"><?php echo $this->translate('Clippings'); ?></a></span>
        <span><a href="<?php echo $this->url('site/resource', ['controller' => 'page', 'action' => 'narratives'], ['query' => ''], true);?>">Narratives</a>
        <span class="active">Docutubes</span>
      <?php endif; ?>
    </h1>
    <?php if($this->heading != 'Docutubes'):?>
      <div id="lang-switcher" class="ui-dropdown-list browse-switch">
          <?php
            $languages = array('de' => 'DE','en'=> 'EN','es' => 'ES','et' => 'ET','fr' => 'FR',
            'mk' => 'MK','nl' => 'NL'
            );
          
            if($this->heading == 'Narratives'):
              $path = $this->url('site/resource',['controller' => 'page', 'action' => 'narratives'], ['query' => ''], true);
            else:
              $path = $this->url('site/resource',['controller' => 'page', 'action' => 'clippings'], ['query' => ''], true);
            endif;
          ?>
          <h2 class="visuallyhidden">Sprache wählen</h2>
          <?php foreach ($languages as $locale => $language): ?>
            <?php if ($locale == $lang): ?>
                <h4 class="ui-dropdown-list-trigger">
                  <span class="visuallyhidden">Aktuelle Sprache: </span>
                   Language <strong><?php echo $language ?></strong></h4>
            <?php endif; ?>
          <?php endforeach; ?>
          <ul>
          <?php foreach ($languages as $locale => $language): ?>
              <?php if ($locale != $lang): ?>
                   <li><a href="<?php echo str_replace($lang,$locale,$path);?>">
                       <?php echo $language ?>
                   </a></li>
              <?php endif;?>
          <?php endforeach; ?>
          </ul>
        </div>
    <?php endif;?>
    <?php if($this->heading != 'Docutubes'):?>
      <div id="search">
          <?php
          $searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
          ?>

          <form action="<?php echo $this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
      );?>" id="search-form">
              <input type="text" name="fulltext_search" value="<?php echo $searchValue; ?>"
                  placeholder="<?php echo $translate('Search the clippings'); ?>"
                  aria-label="<?php echo $translate('Search the clippings'); ?>">
              <button type="submit"><?php echo $translate('Search'); ?></button>
          </form>
      </div>
      <?php if($this->heading != 'Narratives' && $this->heading != 'Docutubes'):?>
        <br> 
        <?php if($lang == 'en'):?>
          <p>Ever wondered about how people in the past dealt with differences and conflicts between different religions? Welcome to the RETOPEA collection! Here you can discover examples of how people in Europe and beyond, in many different historical periods, have thought about and experienced different religious beliefs and practices and found ways of living together. Our collection includes more than 400 &lsquo;clippings&rsquo;. These are short texts, images or videos that explore different aspects of religious diversity, tolerance and peace from many different countries in the past and present. Some of the examples covered may be very familiar to you - others may reveal new insights and surprise you.&nbsp;</p>
          <p>The clippings cover 12 themes - you can click on each of these themes to help you find what is of most interest to you. You can also search the RETOPEA collection using your own search terms. When you find a clipping that particularly catches your attention, check out the heading &lsquo;Is referenced by&rsquo; as this leads you to other related clippings you might find interesting.</p>
          <p>You can explore the RETOPEA collection by yourself - but the clippings can also be used as educational materials in schools, museums or youth groups.&nbsp;</p>
          <p>Each clipping comes with a set of questions to encourage critical thinking about the issues it raises. &nbsp;</p>
          <p>The RETOPEA team have developed a model for workshops where teenagers make short films inspired by the RETOPEA clippings. We call these films &lsquo;docutubes&rsquo; as they are similar in style to Vlogging videos on YouTube. If you are a teacher or educator and would like to find out how to run a docutube workshop yourself or about other ways you can use the RETOPEA resources with your students - <a href="https://retopea.eu/s/start/page/contact">please click here</a>.</p>
        <?php elseif($lang == 'es'):?>
          <p>¿Te has preguntado alguna vez cómo se enfrentaban las personas del pasado a las diferencias y conflictos entre las distintas religiones? Te damos la bienvenida a la colección RETOPEA. Aquí podrás descubrir ejemplos de cómo la gente en Europa y más allá, en muchos períodos históricos diferentes, ha pensado y experimentado diferentes creencias y prácticas religiosas y ha encontrado maneras de vivir juntos. Nuestra colección incluye más de 400 "fragmentos". Se trata de textos breves, imágenes o vídeos que exploran diferentes aspectos de la diversidad religiosa, la tolerancia y la paz en muchos países diferentes, en el pasado y en el presente. Algunos de los ejemplos tratados pueden resultarte muy familiares, mientras que otros pueden revelar nuevas ideas y sorprenderte.</p>
          <p>Los fragmentos abarcan 12 temas; puedes hacer clic en cada uno de ellos para encontrar el que más le interese. También puedes buscar en la colección RETOPEA utilizando tus propios términos de búsqueda. Cuando encuentres un recorte que le llame especialmente la atención, consulta el apartado "Está referenciado por", ya que te llevará a otros fragmentos relacionados que pueden resultarte interesantes.</p>
          <p>Puedes explorar la colección RETOPEA por tu cuenta, pero los fragmentoss también pueden utilizarse como material educativo en escuelas, museos o grupos de jóvenes. </p>
          <p>Cada fragmento viene acompañado de una serie de preguntas para fomentar el pensamiento crítico sobre los temas que plantea.  </p>
          <p>El equipo de RETOPEA ha desarrollado un modelo de talleres en los que los y las adolescentes realizan cortometrajes inspirados en los fragmentos de RETOPEA. Llamamos a estas películas "docutubes", ya que su estilo es similar al de los vídeos de Vlogging en YouTube. Si eres profesor o educador y quieres saber cómo organizar un taller de docutubes o cómo utilizar los recursos de RETOPEA con tus alumnos, haz clic aquí.</p>
        <?php elseif($lang == 'nl'):?>    
          <p>Heb je je ooit afgevraagd hoe mensen in het verleden omgingen met de verschillen en conflicten tussen religies? Welkom bij de RETOPEA-collectie! Hier vind je tal van voorbeelden van hoe mensen doorheen verschillende tijdvakken, en dit zowel in Europa als daarbuiten, hebben nagedacht over de verschillen tussen religieuze overtuigingen, en over hoe ze vanuit hun ervaringen manieren vonden om samen te leven. </p>
          <p>Onze collectie omvat meer dan 400 'knipsels'. Dat zijn korte teksten, beelden of video's die aspecten van religieuze diversiteit, tolerantie en vrede belichten, dit in tal van landen en historische periodes. Sommige voorbeelden zijn je misschien al bekend, andere zullen je beslist verrassen en nieuwe inzichten bijbrengen.</p>
          <p>De knipsels bestrijken 12 thema’s waar je op kan doorklikken. Je kan de RETOPEA-collectie ook doorzoeken met uw eigen zoektermen. Wanneer je op een interessant knipsel stoot, kijk dan zeker ook eens naar de rubriek 'Is referenced by'. Die leidt je naar verwante en misschien ook interessante bronnen.</p>
          <p>Je kan de RETOPEA-collectie vrij verkennen. Maar de knipsels kunnen ook worden gebruikt als educatief materiaal in scholen, musea of jeugdgroepen. </p>
          <p>Bij elk knipsel hoort een reeks vragen die aanzetten tot kritisch denken over de behandelde onderwerpen.</p>
          <p>Het RETOPEA-team heeft een model ontwikkeld voor workshops waar tieners zelf korte films maken, geïnspireerd op de RETOPEA-knipsels. We noemen deze films 'docutubes' omdat ze qua stijl lijken op vlogvideo's op YouTube. Ben je leraar of opvoeder bent en wil je meer info over hoe zelf met je leerlingen een docutube-workshop te organiseren en daarvoor de RETOPEA-bronnen te gebruiken, klik dan hier.</p>
        <?php elseif($lang == 'mk'):?>    
          <p>Дали некогаш сте се запрашале како луѓето во минатото се справувале со разликите и конфликтите меѓу различните религии? Добредојдовте во збирката на RETOPEA! Овде можете да откриете примери за тоа како луѓето во Европа и пошироко, во многу различни историски периоди, размислувале и доживеале различни религиозни верувања и практики и нашле начини за заеднички живот. Нашата збирка вклучува повеќе од 400 “исечоци“. Тоа се кратки текстови, слики или видеа кои истражуваат различни аспекти на верската различност, толеранција и мир од многу различни земји во минатото и сегашноста. Некои од опфатените примери можеби ви се многу познати - други може да откријат нови сознанија и да ве изненадат.</p>
          <p>Исечоците опфаќаат 12 теми - можете да кликнете на секоја од овие теми за да ви помогне да го пронајдете она што најмногу ве интересира. Можете исто така да ја пребарувате збирката на RETOPEA користејќи ги вашите сопствени термини за пребарување. Кога ќе најдете исечок што особено ви го привлекува вниманието, проверете го насловот “Се референцира со“  бидејќи тоа ве води до други поврзани исечоци што можеби ќе ви бидат интересни.</p>
          <p>Можете сами да ја истражите збирката RETOPEA - но исечоците може да се користат и како едукативни материјали во училишта, музеите или страна на групи од млади луѓе.</p>
          <p>Секој исечок доаѓа со збир на прашања за поттикнување на критичко размислување за прашањата што ги отвара.</p>
          <p>Тимот на RETOPEA разви модел за работилници каде што тинејџерите снимаат кратки филмови инспирирани од исечоците од RETOPEA. Овие филмови ги нарекуваме “докутуби“ бидејќи по стил се слични на видеата за блогирање на You Tube. Ако сте наставник или едукатор и сакате да дознаете како сами може да водите работилница за doкутуби или за други начини на кои можете да ги користите ресурсите на RETOPEA со вашите ученици - ве молиме кликнете овде.</p>
        <?php elseif($lang == 'et'):?>      
          <p>Kas olete kunagi mõelnud, kuidas inimesed minevikus tegelesid erinevate religioonide vahel tekkinud lahkhelide ja konfliktidega? Tere tulemast tutvuma RETOPEA koguga! Siin leiate näiteid sellest, kuidas inimesed erinevatel ajalooperioodidel Euroopas ja mujal kogesid erinevaid usundeid ja tavasid, nende üle mõtisklesid ning leidsid kooselamise viise. Meie kogus on üle 400 "väljalõike". Need on lühikesed tekstid, pildid või videod, mis uurivad usulise mitmekesisuse, sallivuse ja rahu erinevaid aspekte paljudest erinevatest riikidest minevikus ja tänapäeval. Mõned näited võivad olla teile väga tuttavad - teised võivad teile uusi teadmisi anda ja teid üllatada. </p>
          <p>Väljalõiked hõlmavad 12 teemat - võite klõpsata igale teemale, et leida teie jaoks kõige huvitavam. Samuti saate RETOPEA kogust otsingusõnu kasutades teemasid otsida. Kui leiate väljalõike, mis äratab teie tähelepanu, vaadake pealkirja "on viidatud", sest see viib teid teiste seotud väljavõtete juurde, mis võivad teid huvitada.</p>
          <p>RETOPEA kogu saate uurida ise, kuid väljalõikeid saab kasutada ka õppematerjalina koolides, muuseumides või noortegruppides. </p>
          <p>Iga väljalõige on varustatud küsimuste kogumiga, et julgustada kriitilist mõtlemist selles tõstatatud teemade üle.  </p>
          <p>RETOPEA meeskond on välja töötanud mudeli töötubade jaoks, kus teismelised teevad RETOPEA väljalõigetest inspireeritud lühifilme. Me nimetame neid filme "veebidokkideks", kuna need on oma stiililt sarnased YouTube'i videoblogide klippidega. Kui oled õpetaja või koolitaja ja soovid teada saada, kuidas ise veebidoki töötuba korraldada või milliseid muid võimalusi leidub RETOPEA ressursside kasutamiseks koos oma õpilastega, siis kliki siia.</p>
        <?php elseif($lang == 'de'):?>
          <p>Hast du dich jemals gefragt, wie Menschen in der Vergangenheit mit Unterschieden und Konflikten zwischen verschiedenen Religionen umgegangen sind? Willkommen in der RETOPEA-Sammlung! Hier kannst du Beispiele dafür entdecken, wie Menschen in Europa und darüber hinaus in verschiedenen historischen Epochen über unterschiedliche religiöse Überzeugungen und Gebräuche gedacht haben und wie sie Wege des Zusammenlebens gefunden haben. Unsere Sammlung umfasst mehr als 400 "Clippings". Dabei handelt es sich um kurze Texte, Bilder oder Videos, die verschiedene Aspekte von religiöser Vielfalt, Toleranz und Frieden aus vielen verschiedenen Ländern in Vergangenheit und Gegenwart beleuchten. Einige der behandelten Beispiele werden dir vielleicht sehr vertraut sein – andere können dir neue Einsichten vermitteln und dich überraschen.</p>
          <p>Die Clippings decken 12 Themen ab – du kannst jedes dieser Themen anklicken, um das zu finden, was für dich am interessantesten ist. Du kannst die RETOPEA-Sammlung auch mit deinen eigenen Suchbegriffen durchsuchen. Wenn du ein Clipping findest, das deine Aufmerksamkeit erregt, solltest du auf den Hinweis "Wird referenziert von" achten, da dieser dich zu anderen verwandten Clippings führt, die für dich auch interessant sein könnten.</p>
          <p>Du kannst die RETOPEA-Sammlung auf eigene Faust erkunden – die Clippings können aber auch als Unterrichtsmaterial in Schulen, Museen oder Jugendgruppen verwendet werden. </p>
          <p>Zu jedem Clipping gibt es eine Reihe von Fragen, die zum kritischen Nachdenken über die darin angesprochenen Themen anregen sollen.  </p>
          <p>Das RETOPEA-Team hat ein Modell für Workshops entwickelt, in denen Jugendliche Kurzfilme drehen, die von den RETOPEA-Clippings inspiriert sind. Wir nennen diese Filme 'Docutubes', da sie dem Stil von Vlogging-Videos auf YouTube ähneln. Wenn Sie Lehrer oder Erzieher sind und wissen möchten, wie Sie selbst einen Docutube-Workshop durchführen oder wie Sie die RETOPEA-Ressourcen mit Ihren Schülern nutzen können, klicken Sie bitte hier.</p>
        <?php elseif($lang == 'fr'):?>  
          <p>Vous êtes-vous déjà demandé comment les différences et les conflits entre les différentes religions étaient traités dans le passé ? Bienvenue dans la collection RETOPEA ! Vous y découvrirez des exemples de la façon dont les gens en Europe et au-delà, à différentes périodes historiques, ont pensé et vécu les différentes croyances et pratiques religieuses et ont trouvé des moyens de vivre ensemble. Notre collection comprend plus de 400 "coupures". Il s'agit de courts textes, d'images ou de vidéos qui explorent différents aspects de la diversité religieuse, de la tolérance et de la paix dans de nombreux pays du passé et du présent. Certains des exemples couverts peuvent vous être très familiers - d'autres peuvent vous révéler de nouvelles perspectives et vous surprendre.  </p>
          <p>Les coupures couvrent 12 thèmes - vous pouvez cliquer sur chacun de ces thèmes pour vous aider à trouver ce qui vous intéresse le plus. Vous pouvez également effectuer une recherche dans la collection RETOPEA en utilisant vos propres termes de recherche. Lorsque vous trouvez une coupure qui retient particulièrement votre attention, vérifiez la rubrique "Est référencée par" car elle vous conduit à d'autres coupures connexes qui pourraient vous intéresser. </p>
          <p>Vous pouvez explorer la collection RETOPEA par intérêt personnel, mais les coupures peuvent également être utilisées comme matériel pédagogique dans les écoles, les musées ou avec les groupes de jeunes.  </p>
          <p>Chaque coupure est accompagnée d'une série de questions visant à encourager la réflexion critique sur les problèmes qu'elle soulève.   </p>
          <p>L'équipe RETOPEA a mis au point un modèle d'atelier dans lequel les adolescents réalisent des courts métrages inspirés des coupures RETOPEA. Nous appelons ces films "docutubes" car leur style est similaire à celui des vidéos des vlogueurs sur YouTube. Si vous êtes un enseignant ou un éducateur et que vous souhaitez savoir comment organiser vous-même un atelier docutube ou découvrir d'autres façons d'utiliser les ressources RETOPEA avec votre public cible, veuillez cliquer ici. </p>
        <?php endif;?>
      
          
      <?php endif;?>    
    <?php endif;?>
    
    <?php echo $this->searchFilters(); ?>
  </div>
<?php endif;?>
<?php if($this->resourceType == 'item-set'):?>
  <div class="item-showcase item-set-showcase">
      <?php foreach ($this->resources as $itemSet): ?>
      <div class="item resource">
        <?php if($media = $itemSet->thumbnail()):?>
          <a href="<?php echo $itemSet->url();?>">
          <div class="media" style="background:url(<?php echo $media->assetUrl('square')?>)"></div>
          </a>
        <?php else:?>
          <div class="media" style="background:#ccc;"></div>
        <?php endif;?>
        <div class="text">
          <?php if($itemSet->value('dcterms:title',array('lang' => $lang))):?>
            <h4><?php echo $itemSet->link($itemSet->value('dcterms:title',array('lang' => $lang))); ?></h4>
          <?php else:?>
            <h4><?php echo $itemSet->link($itemSet->value('dcterms:title')); ?></h4>  
          <?php endif;?> 
        </div>
      </div>
      <?php endforeach; ?>
  </div>

<?php elseif ($this->linkText == 'Browse all news'):?>
  <div class="resource-list preview">
  <?php
  $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
  $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
  foreach ($this->resources as $resource):
      $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
      $body = $resource->value($bodyTerm);
  ?>
      <div class="news-item">
        <div class="thumbnail">
          <?php echo $resource->linkRaw($this->thumbnail($resource, 'square')); ?>
        </div>
        <div class="body">
          <h4><?php echo $resource->link($heading); ?></h4>
          <div class="date">
            <?php if($resource->value('dcterms:date')):?>
              <?php echo date('d-m-Y',strtotime($resource->value('dcterms:date')));?>
            <?php endif;?>
          </div>
          <div class="description">
            <?php if($resource->value('dcterms:alternative')):?>
              <?php echo $resource->value('dcterms:alternative');?>
            <?php endif;?>
          </div>
          <div class="subject">
            <?php if($resource->value('dcterms:subject')):?>
              <?php echo $resource->value('dcterms:subject');?>
            <?php endif;?>
          </div>
        </div>
      </div>
  <?php endforeach; ?>
  <?php
  if ($this->linkText):
      echo $this->hyperlink($this->linkText, $this->url(
          'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
      ));
  endif;
  ?>
  </div>
<?php else:?>
    <div class="resource-list masonry preview homepage">
    <?php
    $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
    $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
    foreach ($this->resources as $resource):
        $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
        $body = $resource->value($bodyTerm);
        $type = $resource->resourceTemplate();
        if($type){
          $type = $resource->resourceTemplate()->label();
        }else{
          $type = false;
        }
    ?>
        <div class="<?php echo $this->resourceType; ?> resource">
          <a href="https://retopea.eu/s/en/item/<?php echo $resource->id();?>"><?php echo $this->thumbnail($resource, 'square'); ?></a>
          <div class="body">
            <h4><a href="https://retopea.eu/s/en/item/<?php echo $resource->id();?>"><?php echo $heading; ?></a></h4>
            <?php if ($body): ?>
              <!--<div class="description"><?php echo $body; ?></div>-->
            <?php endif; ?>
            <?php if ($type == 'Docutube'): ?>
              <div class="language"><?php echo $resource->value('dcterms:language');?></div>
            <?php endif;?>
          </div>
        </div>
    <?php endforeach; ?>
    </div>
    <div class="more-news-showcase">
      <a class="btn" href="https://retopea.eu/s/en/page/clippings"><?php echo $this->linkText;?></a>
    </div>
<?php endif;?>


</div>
<script>

        $('#lang-switcher').find('.ui-dropdown-list-trigger').each(function() {
        	$(this).click(function(){
      			$(this).parent().toggleClass('active');
      		});
        });

        $('.ui-dropdown-list-trigger').click(function(){
      			$(this).parent().toggleClass('active');

        });
</script>
