<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

$libis = $this->plugin('Libis');
$lang = $libis->getLanguage();
$news = false;
?>

<?php $itemSets = $item->itemSets(); ?>
<?php if (count($itemSets) > 0): ?>
<?php
  foreach ($item->itemSets() as $itemSet):
    if($itemSet->displayTitle() == 'News'):
      $news = true;
    endif;
  endforeach;
?>
<?php endif; ?>

<?php if($news):?>
  <nav class="breadcrumbs"><a href="/s/start/page/news">News</a> &gt; <?php echo $item->value('dcterms:title'); ?></nav>
  <div class="news-item">
    <div class="thumbnail">
      <?php echo $this->thumbnail($item, 'medium'); ?>
    </div>
    <div class="body">
      <h3><?php echo $item->value('dcterms:title'); ?></h3>
      <div class="date">
        <?php if($item->value('dcterms:date')):?>
          <?php echo $item->value('dcterms:date');?>
        <?php endif;?>
      </div>
      <div class="description">
        <?php if($item->value('dcterms:description')):?>
          <?php echo $item->value('dcterms:description');?>
        <?php endif;?>
      </div>
      <div class="subject">
        <?php if($item->value('dcterms:subject')):?>
          <?php echo $item->value('dcterms:subject');?>
        <?php endif;?>
      </div>
    </div>
  </div>
<?php else: ?>

<h1>
  <?php
    $title = $item->value('dcterms:title',array('all' => 'true','lang' => $lang));
    if($title):
      echo implode(", ",$title);
    endif;
  ?>
</h1>

<?php $this->trigger('view.show.before'); ?>
<?php 
$lang_media = array();
foreach($itemMedia as $media):
  if($media->hasThumbnails()):
    $lang_media[] = $media;
  elseif($media->value('dcterms:language')):
    if($media->value('dcterms:language') == $lang):
      $lang_media[] = $media;   
    endif; 
  else:
    $lang_media[] = $media;   
  endif;  
endforeach;
//$lang_media = $itemMedia;
?>
<div class="item-show">
  <?php if ($embedMedia && $lang_media): ?>
      <div class="media-embeds">
      <?php foreach ($lang_media as $media):?>
        <div class="media-block <?php echo $media->renderer();?>">
          <?php
            $render =  $media->render().'';
            //var_dump($render);
            $render =  str_replace('http:','',$render);
            $render = str_replace('http&#x3A;','',$render);
            echo $render;
            if($media->hasThumbnails()):
              if($media->value('dcterms:title')):?>
                <div class="caption">
                  <div class="caption-button">
                    <i class="fas fa-info-circle"></i>
                  </div>
                  <a href="<?php echo $site->url()."/media/".$media->id();?>"><?php echo $media->value('dcterms:title');?></a>
                </div>
              <?php else:?>
                <div class="caption">
                  <div class="caption-button">
                    <i class="fas fa-info-circle"></i>
                  </div>
                  <a href="<?php echo $site->url()."/media/".$media->id();?>">More info</a>
                </div>
              <?php endif;?>
            <?php endif;?>
        </div>
      <?php endforeach;
      ?>
      </div>
  <?php endif; ?>

  <?php //echo $this->translator->getLocale();?>
  <div class="metadata">
    <?php echo $item->displayValues(); ?>
    <?php $values = $item->values(); ?>
    <?php //foreach($values as $key=>$value):?>
        <?php //echo $item->value('dcterms:title',array('all' => 'true','lang' => $lang));?>
    <?php //endforeach;?>


    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <h4 class="toggle-trigger"><?php echo $this->translate('Collection'); ?></h4>
        <div class="values toggle-container">
          <?php foreach ($item->itemSets() as $itemSet): ?>
          <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->value('dcterms:title',['lang' => $lang]); ?></a></div>
          <?php endforeach; ?>
        </div>
        <?php endif; ?>

    </div>
  </div>

</div>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<!--<div id="item-linked">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>-->
<?php endif; ?>

<script type="text/javascript">
$(document).ready(function(){
  $(".toggle-trigger").click(function(){
      $(this).toggleClass("toggle-trigger-active").next().toggleClass("toggle-container-opened");
      return false; //Prevent the browser jump to the link anchor
  });
});
</script>
<?php $this->trigger('view.show.after'); ?>
<?php endif;?>
