<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$libis = $this->plugin('Libis');
$slug = $libis->getLanguage();
$lang = $this->lang();
?>
<?php foreach ($values as $term => $propertyData): ?>
    <div class="property">
        <?php if ($term == "dcterms:title" || $term == "dcterms:description" || $term == "dcterms:instructionalMethod"): ?>
          <h4 class="toggle-trigger toggle-trigger-active">
        <?php else: ?>
          <h4 class="toggle-trigger">
        <?php endif; ?>

        <?php if ($propertyData['alternate_label']): ?>
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
        <?php echo $escape($this->translate($propertyData['property']->label())); ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
        </h4>
        <?php if ($term == "dcterms:title" || $term == "dcterms:description" || $term == "dcterms:instructionalMethod"): ?>
          <div class="values toggle-container toggle-container-opened">
        <?php else: ?>
          <div class="values toggle-container">
        <?php endif; ?>
        <?php foreach ($propertyData['values'] as $value):
            $babel = '';
            $class = 'value';
            if ('resource' == $value->type()) {
                $valueResource = $value->valueResource();
                $class .= ' resource ' . $escape($valueResource->resourceName());
            } elseif ('uri' == $value->type()) {
                $class .= ' uri';
            }

            //add more terms
            $babelterms = array('Spatial Coverage','Subject', 'Contributor', 'Cultural Form Of');

            if(in_array($propertyData['property']->label(),$babelterms) && $slug != 'start'):
              $service_url = 'http://babelnet.io/v5/getSenses';

              $lemma = $value->asHtml();
              $searchLang = 'EN';
              $key  = '00a453da-5bea-406b-b107-5c349ba9d6f4';

              //more languages needed
              $language = array(
                'en_US' => 'EN',
                'fr' => 'FR',
                'nl_NL' => 'NL',
                'de_DE' => 'DE',
                'es' => 'ES',
                'pl' => 'PL',
                'it' => 'IT'
              );
              //echo $this->lang();
              if(isset($language[$this->lang()])){
                $targetLang = $language[$this->lang()];
              }else{
                $targetLang = 'EN';
              }

              $params = array(
                'lemma' => $lemma,
                'searchLang'  => $searchLang,
                'targetLang' => $targetLang,
                'key'   => $key,
                'source' => 'WIKT'
              );

              if($targetLang != 'EN'):
                $url = $service_url . '?' . http_build_query($params);

                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($ch, CURLOPT_ENCODING, 'gzip');
                $response = json_decode(curl_exec($ch), true);
                curl_close($ch);

                if($response):
                  $result = $response[0]['properties'];
                  $lemma = $result['fullLemma'];
                  $lemma = str_replace('_',' ',$lemma);
                  $source = $result['source'];
                  $babel = $lemma.' <a target="_blank" href="http://live.babelnet.org/synset?word='.$result['synsetID']['id'].'&details=1&lang='.$targetLang.'"><img alt="link to babelnet" style="height:12px;margin:0 0 0.1rem 2px;" src="'.$this->assetUrl('images/bbnet.png').'" /></a>';
                endif;
              endif;
            endif;
            ?>

            <div class="<?php echo $class; ?>" lang="<?php echo $escape($value->lang()); ?>">
                <!--<?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>-->
                <?php echo ($babel) ? $babel : $value->asHtml();?>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
