<?php
  $escape = $this->plugin('escapeHtml');
  $translate = $this->plugin('translate');
?>

<?php if (count($filters) > 0): ?>
<div class="search-filters">
    <?php foreach ($filters as $filterLabel => $filterValues): ?>
    <div class="filter">
      <?php if($filterLabel != 'Search full-text'):?>
        <span class="filter-label"><?php echo $escape($filterLabel); ?></span>
      <?php else:?>
        <span class="filter-label"><?php echo $this->translate('Search');?></span>
      <?php endif;?>
        <?php foreach ($filterValues as $filterValue): ?>
        <span class="filter-value"><?php echo $escape($filterValue); ?></span>
        <?php endforeach; ?>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
